version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable

    steps:
      - checkout
 
      - run:
          name: Install Dependencies
          command: |
            poetry install

      - run:
          name: Run Tests
          command: |
            poetry run pytest
            
